[[d1_databases]]
binding = "DB"
database_name = "zentube"
database_id = "d32af7fa-dc7e-4102-9a7c-f29f01b6f72c"
migrations_dir = "prisma/migrations"

[site]
bucket = ".next"

[env]
NEXT_VERSION = "16.2.6"
NODE_VERSION = "22.22.2"
